export const projects = [
    {
        id: 0,
        title: "Hack Canada: AutoniMake",
        description_simple: "A plug-and-play AI vision platform that lets anyone train a camera to recognize faces, gestures, or objects in minutes and control robotic peripherals accordingly.",
        description: ["In 20 minutes, we trained a rover to navigate by recognizing our faces. In another 20, we built a sign language translator from scratch. Same camera, same platform, different peripherals. Autonimake is hitting at what machine intelligence is headed towards: a plug-and-play AI vision platform for robotics, but built in under 36 hours for Hack Canada.", 
                        "The idea came from how up to 80% of robotics development time goes toward system integration rather than the actual application. The tools and the AI exist, but getting them to work together is still a hurdle, especially without a background in machine learning. Our solution is to simply open our web app (built with Google Antigravity), take videos of whatever you want to recognize, whether it’s faces, gestures, or objects, and tag them with names. Less than half an hour later our lightweight CNN built with PyTorch is ready.", 
                        "Predictions are sent using from our Raspberry Pi hub over USBc cables to ESP32-based peripherals, controlling whatever you have connected. For example, a drivebase, a display, a robotic arm. We built this for anyone who has a problem that needs a robot but not the resources to build one from scratch. The same camera that steered our rover with faces was translating sign language less than an hour later."],
        image: "/projects/IMG_0420.jpg",
        tags: ["PyTorch", "OpenCV", "Raspberry Pi", "UART", "ESP32"],
        projectLink: "https://github.com/Aabjosh/Autonimake/blob/main/README.md",
    },
    {
        id: 0,
        title: "S26 Toyota Innovation Challenge Submission (TAQA)",
        description_simple: "Award-winning manufacturing assistant combining a camera-equipped hard hat, Raspberry Pi, and robotic arm, using computer vision and voice-triggered image capture to automate bin tracking, defect detection, and safety monitoring on a factory floor.",
        description: ["An award-winning project from the S26 Toyota Innovation Challenge, selected by Toyota employees amongst University of Waterloo engineering students, where my team built an intelligent manufacturing assistant combining computer vision, robotics, and voice interaction to improve safety and efficiency on a factory floor, earning the Safety Award for the effort. The project leveraged a custom camera-powered hard hat, Raspberry Pi, and remote computer connected to the robotic arm.", 
                        "My focus was on the hardware and vision side of the system: I built the QR code scanner used to identify and track bins and components moving through the workflow, and developed the Raspberry Pi interface that tied the physical hardware into the rest of the platform. I also handled the camera integration, capturing images reliably so the vision system could feed real data to the rest of the pipeline, supporting both bin localization and defect detection running elsewhere in the project. I also connected the voice activation system, built by a teammate, to the camera so spoken commands could directly trigger image capture.", 
                        "This meant dealing with actual hardware constraints, not just software, from camera positioning and lighting to making sure the Pi could handle the processing load without becoming a bottleneck for the voice assistant and robotic arm control modules running in parallel. My pieces plugged directly into a larger system where scanned and localized objects triggered downstream inspection and robotic task execution, contributing to a platform recognized for improving both safety and automation on the manufacturing floor."],
        image: "/projects/TIC_S26.jpg",
        tags: ["OpenCV", "Raspberry Pi", "Robotics", "Smart Device"],
        projectLink: "https://github.com/zabsy/toyota-innovation-challenge/blob/main/README.md",
    },
    {
        id: 0,
        title: "KidsAbility: Autobat",
        description_simple: "A microcontroller-powered T-ball batting system designed for children at KidsAbility with motor impairments, enabling accessible and independent play through the push of a button.",
        description: ["A ten-year-old who couldn't grip a bat now launches one with the push of a button. That's Autobat: a fully mobile, automated batting arm I built for KidsAbility to give kids with muscular and coordination challenges a way to play t-ball alongside their peers, without needing the fine motor control that traditional swinging requires.", 
                        "At its core is a custom power distribution board I designed and machined myself, feeding a right-angle drive I also built by hand, paired with off-the-shelf planetary gearboxes to handle torque transmission cleanly and reliably. The whole system runs through an Arduino-based control system, with LED indicators built in to warn nearby kids and staff before the arm activates, keeping the device safe to use around a group of children.", 
                        "I prototyped every mechanical component in Autodesk Inventor before machining and assembling the final unit with real power tools, not just simulations. The end result came in at roughly $500 total, about 10 times cheaper than comparable industrial adaptive batting systems, which made it realistic for KidsAbility to actually deploy rather than shelve as too expensive. Autobat has since been used at a supportive children's league event, letting kids participate in a normal part of childhood that's usually closed off to them, and it's one of the projects that directly fed into the 50-100+ youth I've impacted so far."],
        image: "/projects/Screenshot 2025-07-18 201247.png",
        tags: ["Arduino", "C / C++", "SOLIDWORKS", "Dot Solder Board"],
        projectLink: "https://github.com/Aabjosh/KidsAbility-Autobat/blob/main/README.md",
    },
    {
        id: 0,
        title: "KidsAbility: 3D Printed Aids",
        description_simple: "3D-printed communication aids and playdoh-compatible braille stamps for children at KidsAbility, giving kids with speech, anxiety, or visual challenges a tactile way to express themselves and engage independently.",
        description: ["I designed and built soft-touch, flexible TPU-printed communication aids for kids facing speech and anxiety challenges, giving them a low-pressure, physical way to express feelings or needs without having to speak up in the moment. I also developed braille stamps used with playdoh, aimed at supporting kids with visual impairments through a tactile, hands-on interface rather than anything digital or screen-based.", 
                        "Every design went through CAD modeling first, then prototyping on a Formlabs Form 2 and a BambuLab X1C, working through iterations to account for print tolerances, orientation, and material choice so the final parts could hold up to daily use by kids.", 
                        "I brought other students onto the project who wanted to learn, giving them the opportunity to grow their CAD skills through hands-on work on real parts."],
        image: "/projects/3d_Aids.jpg",
        tags: ["Autodesk Inventor", "SOLIDWORKS"],
        projectLink: "NO_LINK",
    },
    {
        id: 0,
        title: "StrobeShield",
        description_simple: "An award-winning hackathon project glasses that use flickering light-triggered photoresistors to polarize their lenses and prevent photo epilepsy seizures, with real-time event logging.",
        description: ["StrobeShield won Best Hardware Hack at EurekaHACKS. It's a pair of glasses that catches fast, seizure-triggering light flashes and polarizes the lenses right when it detects one, to help protect people with photosensitive epilepsy.",
                        "I helped design the full schematic, wiring together a Raspberry Pi, a motor for the polarizing mechanism, and photoresistors to pick up changes in light hitting the lenses. I also did all the CAD work, modeling every 3D printed part that holds the electronics and mounts onto a normal pair of glasses without making them too bulky to wear.", 
                        "On the software side, I wrote the core detection algorithm in MicroPython, tuned to pick up fast flash patterns in real time instead of just reacting to normal changes in ambient light, so it only triggers when there's an actual flash risk. I also built an event logging API that sends data over Wi-Fi, so every flash it catches gets logged, giving a real record over time instead of just a one-time reaction.", 
                        "The hardest part was getting the timing right. The algorithm had to catch a flash fast enough to matter before it could cause a seizure, but still not false-trigger on normal stuff like screen flicker or sunlight through trees."],
        image: "/projects/Screenshot 2025-07-18 201301.png",
        tags: ["Raspberry Pi", "MicroPython", "SOLIDWORKS"],
        projectLink: "https://devpost.com/software/strobeshield",
    },
];